title: Jekyll Dark-Red Theme
description: "A dark-red theme for Jekyll."
lang: en

exclude: [vendor]

# following configurations allow showing thumbnails on post list

# enable/disable thumbnails forcibly
post_thumbnails: false

# this image will shown if the thumbnail was not specified in the post
post_default_thumbnail: "/relative/path/to/<my_default_thumbnail.png>"

# show default thumbnail in the post list if not specified
post_thumbnail_defaults: true